apiVersion: v1
kind: Service
metadata:
  name: eve
spec:
  selector:
    app: eve
  ports:
    - port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve
  labels:
    app: eve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eve
  template:
    metadata:
      name: eve
      labels:
        app: eve
    spec:
      containers:
        - name: eve
          image: gcr.io/smartace-223409/eve:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080